apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: kserve-test
spec:
  predictor:
    serviceAccountName: s3-sa
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-sklearnserver
      storageUri: s3://kubeflow-bucket-iquant000/models/iris/model.joblib
